export enum WikiMenu {
  Magic = 'Magic',
  LightSources = 'Light Sources',
  Welcome = 'Welcome',
  GettingStarted = 'Getting Started',
  Basics = 'Basics',
  Commands = 'Commands',
  Mechanics = 'Mechanics',
  Crafting = 'Crafting',
  Library = 'Library',
  AutoLoot = 'Auto loot',
  Bestiary = 'Bestiary',
  Charms = 'Charms',
  Fishing = 'Fishing',
  Herbalism = 'Herbalism',
  Mining = 'Mining',
  Skinning = 'Skinning',
  PlantingVegetables = 'Planting Vegetables',
  Cooking = 'Cooking',
  WorldChanges = 'World Changes',
  Bosses = 'Bosses',
  Pickholes = 'Pickholes'
}
